# Generated by Django 4.1.3 on 2022-11-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.EmailField(
                max_length=200, unique=True, verbose_name="email address"
            ),
        ),
    ]
