# Generated by Django 4.1.3 on 2022-11-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=200, null=True, verbose_name="username"),
        ),
    ]
