# Generated by Django 4.1.3 on 2022-11-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_message_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="read1",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="avatar.svg", null=True, upload_to=""
            ),
        ),
    ]
