# Generated by Django 4.1.3 on 2022-11-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_message_read_message_read1_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="avatar.svg", null=True, upload_to="images/"
            ),
        ),
    ]
