# Generated by Django 4.1.3 on 2022-12-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_user_email_alter_user_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="online_status",
            field=models.BooleanField(null=True),
        ),
    ]
