# Generated by Django 4.1.3 on 2022-12-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_user_online_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="online_status",
            new_name="is_online",
        ),
    ]
