# Generated by Django 4.1.3 on 2022-12-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_rename_online_status_user_is_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(null=True),
        ),
    ]
