# Generated by Django 4.1.3 on 2022-12-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_user_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
